services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: mp2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"


  mongo:
      image: mongo
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
        MONGO_INITDB_DATABASE: barmagtouny
      ports:
        - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "9000:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  app:
    build: .
    container_name: miniproject2
    depends_on:
      - postgres
      - mongo
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mp2
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      spring.data.mongodb.uri: mongodb://root:example@mongo:27017/barmagtouny?authSource=admin
      spring.data.mongodb.database: barmagtouny



