spring.application.name=MiniProject2

# Class Paths for testing
ModelsPath.Captain=scalable.mini_projects.Mini_Project2.models.Captain
ModelsPath.Customer=scalable.mini_projects.Mini_Project2.models.Customer
ModelsPath.Payment=scalable.mini_projects.Mini_Project2.models.Payment
ModelsPath.Rating=scalable.mini_projects.Mini_Project2.models.Rating
ModelsPath.Trip=scalable.mini_projects.Mini_Project2.models.Trip
spring.datasource.url=jdbc:postgresql://localhost:5432/mp2
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.data.mongodb.uri=mongodb://root:example@localhost:27017/barmagtouny?authSource=admin
spring.data.mongodb.database= barmagtouny
