spring.application.name=MiniProject2

# Class Paths for testing
ModelsPath.Captain=scalable.mini_projects.Mini_Project2.models.Captain
ModelsPath.Customer=scalable.mini_projects.Mini_Project2.models.Customer
ModelsPath.Payment=scalable.mini_projects.Mini_Project2.models.Payment
ModelsPath.Rating=scalable.mini_projects.Mini_Project2.models.Rating
ModelsPath.Trip=scalable.mini_projects.Mini_Project2.models.Trip

spring.data.mongodb.uri=mongodb://root:example@localhost:27017/barmagtouny?authSource=admin
spring.data.mongodb.database= barmagtouny
ModelsPath.Captain = com.example.miniapp.models.Captain 
ModelsPath.Customer = com.example.miniapp.models.Customer
ModelsPath.Payment = com.example.miniapp.models.Payment
ModelsPath.Rating = com.example.miniapp.models.Rating
ModelsPath.Trip = com.example.miniapp.models.Trip
